# Generated by Django 3.0.5 on 2023-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MSC(Comuter Science)', 'MSC(Comuter Science)'), ('M.A(English)', 'M.A(English)'), ('M.A(Hindi)', 'M.A(Hindi)'), ('M.A(History)', 'M.A(History)'), ('M.A(Psychology)', 'M.A(Psychology)'), ('M.A(Sociology)', 'M.A(Sociology)'), ('M.Com', 'M.Com'), ('MBA', 'MBA'), ('M.Lib', 'M.Lib')], default='MCA', max_length=40),
        ),
    ]
